// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOy616BQf-aX-BvKALE9ybYcvaJyLhMo',
    appId: '1:693556635639:web:164cd5a6f9b8e0068a70f2',
    messagingSenderId: '693556635639',
    projectId: 'ngalaman-kelompok-16',
    authDomain: 'ngalaman-kelompok-16.firebaseapp.com',
    storageBucket: 'ngalaman-kelompok-16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxF0wz1qJGBDJyyGSMlfe8aZiFroOXOQk',
    appId: '1:693556635639:android:2a470660f641af518a70f2',
    messagingSenderId: '693556635639',
    projectId: 'ngalaman-kelompok-16',
    storageBucket: 'ngalaman-kelompok-16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsezQg_a5N3181gyp_YKK9OUZ65_PlWVY',
    appId: '1:693556635639:ios:52c87e79be68a36f8a70f2',
    messagingSenderId: '693556635639',
    projectId: 'ngalaman-kelompok-16',
    storageBucket: 'ngalaman-kelompok-16.firebasestorage.app',
    iosBundleId: 'com.example.ngalaman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsezQg_a5N3181gyp_YKK9OUZ65_PlWVY',
    appId: '1:693556635639:ios:52c87e79be68a36f8a70f2',
    messagingSenderId: '693556635639',
    projectId: 'ngalaman-kelompok-16',
    storageBucket: 'ngalaman-kelompok-16.firebasestorage.app',
    iosBundleId: 'com.example.ngalaman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKOy616BQf-aX-BvKALE9ybYcvaJyLhMo',
    appId: '1:693556635639:web:efe1d8469890b7d78a70f2',
    messagingSenderId: '693556635639',
    projectId: 'ngalaman-kelompok-16',
    authDomain: 'ngalaman-kelompok-16.firebaseapp.com',
    storageBucket: 'ngalaman-kelompok-16.firebasestorage.app',
  );
}
